### ISSUE TITLE
Ambiguous field: cannot call non-function gpiod.WithBothEdges (type gpiod.LineEdge)

### ISSUE THREAD

**Issue by mvasi90** [martinohmann/rfoutlet#34]
```bash
go get  -u github.com/martinohmann/rfoutlet/pkg/gpio
# github.com/martinohmann/rfoutlet/pkg/gpio
martinohmann/rfoutlet/pkg/gpio/watcher.go:16:58: cannot call non-function gpiod.WithBothEdges (type gpiod.LineEdge)
```
Maybe this line:
```go
pin, err := chip.RequestLine(offset, gpiod.WithBothEdges(w.handleEvent))

```
should be

```go
pin, err := chip.RequestLine(offset, gpiod.WithEventHandler(w.handleEvent), gpiod.WithBothEdges)
```

<details>
<summary>
Go version
</summary>

Tested on:
go version go1.16.3 linux/arm64
go version go.16.3 linux/amd64
go version go 16.3 linux/arm
</details>

<details>
<summary>
OS
</summary>

Tested on:
ArchLinux 5.11.11-arch1-1 (x86_64)
ArchLinux 5.10.31-6-ARCH (armv7l)
</details>

**Comment by mvasi90** [comment]
Note:  If the `go.mod` file is ignored for privacy reasons, the gpiod version is the latest (v0.6.0) instead of v0.5.0. And it is not compatible without the previous line changed (`...gpiod.WithEventHandler(w.handleEvent),...`)

**Comment by martinohmann** [comment]
Hi! Yeah the latest version of gpiod seems to include breaking API changes. I wanted to set up dependabot to keep the dependencies closer to the latest version but did not get to it yet.

If you like, you can bump `github.com/warthog618/gpiod` to `v0.6.0` and submit a PR with your proposed fix. Thanks!

**Comment by martinohmann** [comment]
@mvasi90 I pushed https://github.com/martinohmann/rfoutlet/releases/tag/v1.2.0 which should resolve your issue.

**Comment by mvasi90** [comment]
@martinohmann I'm very busy and could not answer before.
For privacy reasons I never make PR or publish code (for now).
I opened this issue to notify you of the change (to avoid wasting time researching).

Thank you for the commit #50.

Unrelated:
It would be interesting to program an AVR (attiny85) or ARM (Cortex-m0) as a filter to avoid high processor usage. On Raspberry Pi 2 the CPU usage is 70%.
